// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Action {
	/**
	 * 
	 */
	private int roundNumber;
	/**
	 * 
	 */
	private int playerID;
	/**
	 * 
	 */
	private String description;

	/**
	 * 
	 * @param roundNumber
	 * @param playerID
	 * @param description
	 */
	public Action(int roundNumber, int playerID, String description) {
		this.roundNumber = roundNumber;
		this.playerID = playerID;
		this.description = description;
	}

	/**
	 * 
	 * @return the action description (e.g. BUILD_SETTLEMENT, PASS)
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * 
	 * @return
	 */
	public String toString() {
		return "[" + roundNumber + "] / [" + playerID + "]: " + description;
	}
}