// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public enum ActionType {
	/**
	 * 
	 */
	ROLL,
	/**
	 * 
	 */
	BUILD_SETTLEMENT,
	/**
	 * 
	 */
	BUILD_CITY,
	/**
	 * 
	 */
	/**
	 * 
	 */
	BUILD_ROAD,
	/**
	 * 
	 */
	TRADE,
	/**
	 * 
	 */
	PASS,
	/**
	 * 
	 */
	LIST,
	/**
	 * 
	 */
	UNDO,
	/**
	 * 
	 */
	REDO;
}
