// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.security.SecureRandom;
import java.util.List;
import java.util.Random;

/************************************************************/
/**
 * A machine-controlled agent that makes random decisions.
 * Implements IAgent per the UML.
 */
public class Agent implements IAgent {

    private Player player;
    private Random random;
    private DecisionStrategy strategy;
    private int currentRound = -1;
    private boolean hasRolledThisTurn = false;

    public Agent(Player player) {
        this.player = player;
        this.random = new SecureRandom();
        // Default strategy
        this.strategy = new RandomDecisionStrategy();
    }

    public Agent(Player player, DecisionStrategy strategy) {
        this.player = player;
        this.random = new SecureRandom();
        this.strategy = strategy;
    }

    public void setStrategy(DecisionStrategy strategy) {
        this.strategy = strategy;
    }

    public Player getPlayer() {
        return player;
    }

    /**
     * Rolls two six-sided dice and returns the sum (2–12).
     */
    public int rollDice() {
        return (random.nextInt(6) + 1) + (random.nextInt(6) + 1);
    }

    /**
     * Chooses a random action from the given list, or null if the list is
     * null or empty.
     */
    public Action chooseRandomAction(List<Action> availableActions) {
        if (availableActions == null || availableActions.isEmpty()) {
            return null;
        }
        return availableActions.get(random.nextInt(availableActions.size()));
    }

    /**
     * Turn automaton: roll → resolve → choose action via strategy.
     */
    @Override
    public Action takeTurn(Game game) {
        if (currentRound != game.getRound()) {
            currentRound = game.getRound();
            hasRolledThisTurn = false;
        }

        if (!hasRolledThisTurn) {
            hasRolledThisTurn = true;
            return new Action(currentRound, player.getId(), "ROLL", ActionType.ROLL);
        }

        // Delegate decision making to the strategy
        GameState state = new GameState(game, player);
        Action chosen = strategy.chooseAction(state);
        if (chosen != null && chosen.getActionType() == ActionType.PASS) {
            hasRolledThisTurn = false;
        }
        return chosen;
    }

    /**
     * Convenience: make a decision (delegates to random action selection).
     */
    public Action makeDecision() {
        // Default: pass
        return new Action(0, player.getId(), "PASS", ActionType.PASS);
    }
}
