// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * The game board containing tiles, nodes, and edges.
 * Provides placement legality checks and adjacency queries.
 */
public class Board {

    private List<Tile> tiles;
    private List<Node> nodes;
    private List<Edge> edges;
    private Robber robber;

    public Board(List<Tile> tiles, List<Node> nodes, List<Edge> edges) {
        this.tiles = new ArrayList<>(tiles);
        this.nodes = new ArrayList<>(nodes);
        this.edges = new ArrayList<>(edges);
        this.robber = new Robber();
    }

    // ---- Lookup by ID ----

    public Tile getTile(int id) {
        for (Tile t : tiles) {
            if (t.getId() == id) {
                return t;
            }
        }
        return null;
    }

    public Node getNode(int id) {
        for (Node n : nodes) {
            if (n.getId() == id) {
                return n;
            }
        }
        return null;
    }

    public Edge getEdge(int id) {
        for (Edge e : edges) {
            if (e.getId() == id) {
                return e;
            }
        }
        return null;
    }

    // ---- Placement legality ----

    /**
     * A settlement can be placed on a node during the SETUP PHASE if:
     * 1. The node has no existing structure.
     * 2. No adjacent node already has a structure (distance rule).
     * Connection to existing roads is NOT required during setup.
     */
    public boolean isValidSetupSettlementPlacement(Node node, Player player) {
        if (node == null || player == null) {
            return false;
        }
        if (node.getStructure() != null) {
            return false;
        }
        for (Node adj : getAdjacentNodes(node)) {
            if (adj.getStructure() != null) {
                return false;
            }
        }
        return true;
    }

    /**
     * A settlement can be placed on a node during NORMAL PLAY if:
     * 1. The node has no existing structure.
     * 2. No adjacent node already has a structure (distance rule).
     * 3. The player has a connecting road.
     */
    public boolean isValidSettlementPlacement(Node node, Player player) {
        if (node == null || player == null) {
            return false;
        }
        // Node must be empty
        if (node.getStructure() != null) {
            return false;
        }
        // Distance rule: no adjacent node may have a structure
        List<Node> adjacent = getAdjacentNodes(node);
        for (Node adj : adjacent) {
            if (adj.getStructure() != null) {
                return false;
            }
        }
        // Normal play: must have a connecting road owned by this player
        boolean hasConnectingRoad = false;
        List<Edge> adjEdges = getAdjacentEdges(node);
        for (Edge e : adjEdges) {
            if (e.getRoad() != null && e.getRoad().getOwner().getId() == player.getId()) {
                hasConnectingRoad = true;
                break;
            }
        }
        if (!hasConnectingRoad) {
            return false;
        }
        return true;
    }

    /**
     * A road can be placed on an edge if:
     * 1. The edge has no existing road.
     * 2. The player has a structure or road connected to one end.
     */
    public boolean isValidRoadPlacement(Edge edge, Player player) {
        if (edge == null || player == null || edge.getRoad() != null) {
            return false;
        }
        return canConnectToNetwork(edge, player);
    }

    private boolean canConnectToNetwork(Edge edge, Player player) {
        for (Node n : edge.getNodes()) {
            // Friendly building always allows a road
            if (isFriendlyStructureAt(n, player)) {
                return true;
            }
            // Friendly road allows extension, unless blocked by enemy
            if (!isBlockedByEnemy(n, player) && hasFriendlyConnectingRoad(edge, n, player)) {
                return true;
            }
        }
        return false;
    }

    private boolean isFriendlyStructureAt(Node node, Player player) {
        return node.getStructure() != null && node.getStructure().getOwner().getId() == player.getId();
    }

    private boolean isBlockedByEnemy(Node node, Player player) {
        return node.getStructure() != null && node.getStructure().getOwner().getId() != player.getId();
    }

    private boolean hasFriendlyConnectingRoad(Edge targetEdge, Node node, Player player) {
        List<Edge> adjEdges = getAdjacentEdges(node);
        for (Edge adj : adjEdges) {
            if (adj.getId() != targetEdge.getId() && adj.getRoad() != null
                    && adj.getRoad().getOwner().getId() == player.getId()) {
                return true;
            }
        }
        return false;
    }

    /**
     * A city can be placed on a node if:
     * 1. The node has an existing settlement owned by the player.
     */
    public boolean isValidCityPlacement(Node node, Player player) {
        if (node == null || player == null) {
            return false;
        }
        Structure s = node.getStructure();
        if (s == null) {
            return false;
        }
        return (s instanceof Settlement)
                && s.getOwner().getId() == player.getId();
    }

    // ---- Adjacency queries ----

    /**
     * Returns all nodes adjacent to the given node
     * (connected by an edge that has both nodes set).
     */
    public List<Node> getAdjacentNodes(Node node) {
        List<Node> adjacent = new ArrayList<>();
        for (Edge e : edges) {
            List<Node> eNodes = e.getNodes();
            if (eNodes.size() == 2) {
                if (eNodes.get(0).getId() == node.getId()) {
                    adjacent.add(eNodes.get(1));
                } else if (eNodes.get(1).getId() == node.getId()) {
                    adjacent.add(eNodes.get(0));
                }
            }
        }
        return adjacent;
    }

    /**
     * Returns all edges connected to the given node.
     */
    public List<Edge> getAdjacentEdges(Node node) {
        List<Edge> adjacent = new ArrayList<>();
        for (Edge e : edges) {
            for (Node n : e.getNodes()) {
                if (n.getId() == node.getId()) {
                    adjacent.add(e);
                    break;
                }
            }
        }
        return adjacent;
    }

    /**
     * Returns true if any adjacent node has a structure (used for distance rule).
     */
    public boolean hasAdjacentStructures(Node node) {
        List<Node> adjacent = getAdjacentNodes(node);
        for (Node adj : adjacent) {
            if (adj.getStructure() != null) {
                return true;
            }
        }
        return false;
    }

    // ---- R3.3 Topology Helpers ----

    /**
     * Returns the length of the longest continuous road for the given player.
     * Practical implementation: finds the longest simple path in the road graph.
     */
    public int getLongestRoadLength(Player player) {
        int maxLength = 0;
        List<Edge> playerRoads = getPlayerRoads(player);
        for (Edge start : playerRoads) {
            maxLength = Math.max(maxLength, findLongestPathFrom(start, player, new ArrayList<>()));
        }
        return maxLength;
    }

    private int findLongestPathFrom(Edge current, Player player, List<Edge> visited) {
        visited.add(current);
        int maxNested = 0;
        for (Node n : current.getNodes()) {
            if (isBlockedByEnemy(n, player)) continue;
            List<Edge> adjEdges = getAdjacentEdges(n);
            for (Edge next : adjEdges) {
                if (!visited.contains(next) && next.getRoad() != null && next.getRoad().getOwner().getId() == player.getId()) {
                    maxNested = Math.max(maxNested, findLongestPathFrom(next, player, new ArrayList<>(visited)));
                }
            }
        }
        return 1 + maxNested;
    }

    private List<Edge> getPlayerRoads(Player player) {
        List<Edge> playerRoads = new ArrayList<>();
        for (Edge e : edges) {
            if (e.getRoad() != null && e.getRoad().getOwner().getId() == player.getId()) {
                playerRoads.add(e);
            }
        }
        return playerRoads;
    }

    /**
     * Checks if there are two road segments within two units of each other that could be connected.
     * Returns a candidate edge to build a road on if it helps connect them.
     */
    public Edge getConnectingRoadCandidate(Player player) {
        // R3.3: Max two units away means one intermediate road could connect two segments 
        // OR two intermediate roads. 
        // Simplification: find a legal road placement that connects to a node which is 1-edge 
        // away from another disconnected segment.
        List<Edge> playerRoads = getPlayerRoads(player);
        if (playerRoads.size() < 2) return null;

        for (Edge e : edges) {
            if (isValidRoadPlacement(e, player)) {
                // If we place a road here, does it touch another road segment that was previously disconnected?
                // For simplicity: check if the OTHER node of this edge is adjacent to a different road segment.
                for (Node n : e.getNodes()) {
                    if (hasFriendlyConnectingRoad(e, n, player)) continue; // Already connected at this end
                    
                    // Check if this node is 1 unit away from another player road
                    List<Edge> neighbors = getAdjacentEdges(n);
                    for (Edge neigh : neighbors) {
                        if (neigh.getId() != e.getId() && neigh.getRoad() != null && neigh.getRoad().getOwner().getId() == player.getId()) {
                            // This edge e, if built, would connect current network to 'neigh'.
                            return e; 
                        }
                    }
                }
            }
        }
        return null;
    }

    // ---- Accessors ----

    public List<Tile> getTiles() {
        return tiles;
    }

    public List<Node> getNodes() {
        return nodes;
    }

    public List<Edge> getEdges() {
        return edges;
    }

    public Robber getRobber() {
        return robber;
    }

}
