// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/************************************************************/
/**
 * Parses human-entered commands into Action objects using regular expressions.
 * Responsibility: parsing only — no game logic.
 *
 * Supported commands (case-insensitive):
 * roll
 * list
 * build settlement <nodeId>
 * build city <nodeId>
 * build road <fromNodeId> <toNodeId>
 * pass
 */
public class CommandParser {

    // Patterns compiled once for performance
    private static final Pattern ROLL_PATTERN = Pattern.compile("^\\s*roll\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern LIST_PATTERN = Pattern.compile("^\\s*list\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern PASS_PATTERN = Pattern.compile("^\\s*(pass|go)\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern BUILD_SETTLEMENT_PATTERN = Pattern.compile("^\\s*build\\s+settlement\\s+(\\d+)\\s*$",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern BUILD_CITY_PATTERN = Pattern.compile("^\\s*build\\s+city\\s+(\\d+)\\s*$",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern BUILD_ROAD_PATTERN = Pattern.compile("^\\s*build\\s+road\\s+(\\d+)\\s+(\\d+)\\s*$",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern UNDO_PATTERN = Pattern.compile("^\\s*undo\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern REDO_PATTERN = Pattern.compile("^\\s*redo\\s*$", Pattern.CASE_INSENSITIVE);

    /**
     * Parses the given input string into an Action.
     * Returns null if the input does not match any supported command.
     *
     * @param input the command string entered by the human player
     * @return an Action representing the command, or null if invalid
     */
    public Action parse(String input) {
        if (input == null) {
            return null;
        }

        Matcher m;

        // undo
        m = UNDO_PATTERN.matcher(input);
        if (m.matches()) {
            return new Action(0, 0, "UNDO", ActionType.UNDO);
        }

        // redo
        m = REDO_PATTERN.matcher(input);
        if (m.matches()) {
            return new Action(0, 0, "REDO", ActionType.REDO);
        }

        // roll
        m = ROLL_PATTERN.matcher(input);
        if (m.matches()) {
            return new Action(0, 0, "ROLL", ActionType.ROLL);
        }

        // list
        m = LIST_PATTERN.matcher(input);
        if (m.matches()) {
            return new Action(0, 0, "LIST", ActionType.LIST);
        }

        // pass/go
        m = PASS_PATTERN.matcher(input);
        if (m.matches()) {
            return new Action(0, 0, "PASS", ActionType.PASS);
        }

        // build settlement <nodeId>
        m = BUILD_SETTLEMENT_PATTERN.matcher(input);
        if (m.matches()) {
            int nodeId = Integer.parseInt(m.group(1));
            return new Action(0, 0, "BUILD_SETTLEMENT " + nodeId, ActionType.BUILD_SETTLEMENT);
        }

        // build city <nodeId>
        m = BUILD_CITY_PATTERN.matcher(input);
        if (m.matches()) {
            int nodeId = Integer.parseInt(m.group(1));
            return new Action(0, 0, "BUILD_CITY " + nodeId, ActionType.BUILD_CITY);
        }

        // build road <fromNodeId> <toNodeId>
        m = BUILD_ROAD_PATTERN.matcher(input);
        if (m.matches()) {
            int fromId = Integer.parseInt(m.group(1));
            int toId = Integer.parseInt(m.group(2));
            return new Action(0, 0, "BUILD_ROAD " + fromId + " " + toId, ActionType.BUILD_ROAD);
        }

        return null;
    }

    /**
     * Returns true if the input matches any supported command.
     *
     * @param input the command string
     * @return true if valid, false otherwise
     */
    public boolean isValid(String input) {
        return parse(input) != null;
    }
}
