// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/************************************************************/
/**
 * 
 */
public class Configuration {
	/**
	 * 
	 */
	private int maxRounds;

	/**
	 * 
	 */
	public Configuration() {
		this.maxRounds = 500; // Safety-net maximum; game should end via VP threshold first
	}

	/**
	 * 
	 * @param filePath
	 * @return
	 */
	public void loadFromFile(String filePath) {
		try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
			String line;
			while ((line = reader.readLine()) != null) {
				if (line.startsWith("turns:")) {
					String[] parts = line.split(":");
					if (parts.length == 2) {
						this.maxRounds = Integer.parseInt(parts[1].trim());
					}
				}
			}
		} catch (IOException e) {
			System.err.println("Error reading configuration file: " + e.getMessage());
		} catch (NumberFormatException e) {
			System.err.println("Error parsing maxRounds value: " + e.getMessage());
		}
	}

	/**
	 * 
	 * @return
	 */
	public int getMaxRounds() {
		return maxRounds;
	}
}