// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.ArrayList;
import java.util.List;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

/************************************************************/
/**
 * Entry point for the Catan simulator demonstration.
 * Sets up a game with 3 AI agents and 1 human player,
 * runs the game loop, and exports state for visualization.
 */
public class Demonstrator {
    private static final Logger LOGGER = Logger.getLogger(Demonstrator.class.getName());

    public static void main(String[] args) {
        LOGGER.info("===================================");
        LOGGER.info("   Catan Simulator - Assignment 2  ");
        LOGGER.info("===================================\n");

        // --- Build the board ---
        List<Tile> tiles = createTiles();
        List<Node> nodes = createNodes();
        mapNodesToTiles(tiles, nodes);
        List<Edge> edges = createEdges(nodes);
        Board board = new Board(tiles, nodes, edges);

        // --- Create players ---
        Player p1 = new Player(1);
        Player p2 = new Player(2);
        Player p3 = new Player(3);
        Player p4 = new Player(4); // Blue, Red, Orange, White mapped in visualizer
        List<Player> players = List.of(p1, p2, p3, p4);

        // --- Create agents: 3 AI + 1 Human ---
        List<IAgent> agents = new ArrayList<>();
        DecisionStrategy ruleStrategy = new RuleBasedDecisionStrategy();
        agents.add(new Agent(p1, ruleStrategy)); // AI with Rule-Based Strategy
        agents.add(new Agent(p2, ruleStrategy)); // AI with Rule-Based Strategy
        agents.add(new Agent(p3, ruleStrategy)); // AI with Rule-Based Strategy
        agents.add(new HumanAgent(p4)); // Human (Player 4)

        // --- Create and start the game ---
        Game game = new Game(board, players, agents);
        LOGGER.log(Level.INFO, "Game created with {0} players.", players.size());
        LOGGER.info("Player 4 is the human player.\n");

        // Write the base map and initial state before starting the game
        game.getGameStateExporter().writeBaseMap(board);
        game.getGameStateExporter().writeState(game);

        // Seed initial state // R3.1 setup scenario
        setupVerificationScenario();

        // Run the simulation
        game.startGame();

        // Write the final state
        game.getGameStateExporter().writeState(game);

        LOGGER.info("\nGame simulation concluded.");
        LOGGER.info("Base map and State exported to: base_map.json and state.json");

        // Try launching the python visualizer
        launchVisualizer();

        LOGGER.info("Done.");
    }

    private static void setupVerificationScenario() {
        LOGGER.info(">>> Regular Setup sequence initializing (no pre-seeded Verification Scenario) <<<");
        // We will no longer seed any early structures or resources here,
        // so that the 8-step Setup Phase correctly builds from zero.
    }

    // findEdge method removed as it is no longer used by the verification scenario.

    private static void launchVisualizer() {
        LOGGER.info("Attempting to launch Python Visualizer...");
        try {
            // Find the visualizer script path. We know it's in the adjacent 2026-base
            // folder.
            File visFile = new File("../2aa4-2026-base/assignments/visualize/light_visualizer.py");
            if (!visFile.exists()) {
                LOGGER.log(Level.INFO, "Could not locate visualizer script at: {0}", visFile.getAbsolutePath());
                return;
            }

            ProcessBuilder pb = new ProcessBuilder(
                    "../2aa4-2026-base/assignments/visualize/.venv/bin/python3",
                    visFile.getAbsolutePath(),
                    "base_map.json",
                    "state.json",
                    "--out-dir",
                    "scraped_boards");
            pb.directory(visFile.getParentFile());
            pb.inheritIO(); // Pipe python output to java console
            Process process = pb.start();
            process.waitFor();
        } catch (InterruptedException e) {
            LOGGER.log(Level.SEVERE, "Visualizer process was interrupted", e);
            Thread.currentThread().interrupt();
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Failed to launch visualizer", e);
        }
    }

    // ---- Board Setup Helpers ----

    /**
     * Maps the 6 encompassing nodes for each of the 19 tiles.
     */
    public static void mapNodesToTiles(List<Tile> tiles, List<Node> nodes) {
        // Standard Catan node-to-tile mapping (topology dependent)
        int[][] mapping = {
                { 0, 1, 2, 3, 4, 5 }, // Tile 0
                { 1, 2, 6, 23, 22, 21 }, // Tile 1
                { 2, 3, 9, 8, 7, 6 }, // Tile 2
                { 3, 4, 12, 11, 10, 9 }, // Tile 3
                { 4, 5, 13, 14, 11, 12 }, // Tile 4
                { 0, 5, 13, 15, 18, 17 }, // Tile 5
                { 0, 1, 21, 20, 19, 17 }, // Tile 6
                { 15, 18, 38, 39, 36, 35 }, // Tile 7
                { 5, 13, 15, 35, 34, 14 }, // Tile 8
                { 11, 12, 14, 34, 33, 32 }, // Tile 9
                { 10, 11, 32, 31, 30, 29 }, // Tile 10
                { 8, 9, 10, 29, 28, 27 }, // Tile 11
                { 7, 8, 27, 26, 25, 24 }, // Tile 12
                { 6, 7, 24, 23, 52, 53 }, // Tile 13
                { 22, 23, 52, 51, 50, 49 }, // Tile 14
                { 21, 22, 49, 48, 47, 20 }, // Tile 15
                { 19, 20, 47, 46, 45, 44 }, // Tile 16
                { 16, 17, 19, 44, 43, 41 }, // Tile 17
                { 16, 18, 38, 42, 40, 41 } // Tile 18
        };

        for (int i = 0; i < mapping.length && i < tiles.size(); i++) {
            Tile t = tiles.get(i);
            for (int nodeId : mapping[i]) {
                for (Node n : nodes) {
                    if (n.getId() == nodeId) {
                        t.addNode(n);
                    }
                }
            }
        }
    }

    /**
     * Creates the 19 standard Catan hex tiles.
     */
    public static List<Tile> createTiles() {
        List<Tile> tiles = new ArrayList<>();
        ResourceType[] types = {
                ResourceType.LUMBER, ResourceType.WOOL, ResourceType.GRAIN,
                ResourceType.BRICK, ResourceType.ORE,
                ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL,
                ResourceType.BRICK, ResourceType.GRAIN,
                ResourceType.LUMBER, ResourceType.ORE, ResourceType.LUMBER,
                ResourceType.WOOL, ResourceType.BRICK, ResourceType.WOOL,
                ResourceType.ORE, ResourceType.GRAIN, ResourceType.WOOL
        };
        int[] numbers = { 2, 3, 3, 4, 4, 5, 5, 6, 6, 8, 8, 9, 9, 10, 10, 11, 11, 12, 0 };

        for (int i = 0; i < types.length; i++) {
            tiles.add(new Tile(i, types[i], numbers[i]));
        }
        return tiles;
    }

    /**
     * Creates 54 nodes (standard Catan board intersections).
     */
    public static List<Node> createNodes() {
        List<Node> nodes = new ArrayList<>();
        for (int i = 0; i <= 53; i++) {
            nodes.add(new Node(i));
        }
        return nodes;
    }

    /**
     * Creates 72 edges connecting adjacent nodes.
     * Simplified connectivity for demonstration.
     */
    public static List<Edge> createEdges(List<Node> nodes) {
        List<Edge> edges = new ArrayList<>();
        // Create edges connecting using accurately mapped topology
        int[][] connections = {
                { 0, 1 }, { 0, 5 }, { 0, 20 }, { 1, 2 }, { 1, 6 }, { 2, 3 }, { 2, 9 }, { 3, 4 }, { 3, 12 },
                { 4, 5 }, { 4, 15 }, { 5, 16 }, { 6, 7 }, { 6, 23 }, { 7, 8 }, { 7, 24 }, { 8, 9 }, { 8, 27 },
                { 9, 10 }, { 10, 11 }, { 10, 29 }, { 11, 12 }, { 11, 32 }, { 12, 13 }, { 13, 14 }, { 13, 34 },
                { 14, 15 }, { 14, 37 }, { 15, 17 }, { 16, 5 }, { 16, 18 }, { 16, 21 }, { 17, 39 }, { 17, 18 },
                { 18, 40 },
                { 19, 20 }, { 19, 46 }, { 19, 21 }, { 20, 0 }, { 20, 22 }, { 21, 43 }, { 22, 23 }, { 22, 49 },
                { 23, 52 },
                { 24, 25 }, { 24, 53 }, { 25, 26 }, { 26, 27 }, { 27, 28 }, { 28, 29 }, { 29, 30 }, { 30, 31 },
                { 31, 32 }, { 32, 33 }, { 33, 34 }, { 34, 36 }, { 35, 37 }, { 35, 39 }, { 36, 37 }, { 38, 39 },
                { 38, 42 }, { 40, 41 }, { 40, 42 }, { 41, 43 }, { 43, 44 }, { 44, 45 }, { 45, 46 }, { 46, 47 },
                { 47, 48 }, { 48, 49 }, { 49, 50 }, { 50, 51 }, { 51, 52 }, { 52, 53 }
        };

        for (int i = 0; i < connections.length; i++) {
            Edge e = new Edge(i);
            int fromId = connections[i][0];
            int toId = connections[i][1];
            // Find nodes by ID
            Node from = null;
            Node to = null;
            for (Node n : nodes) {
                if (n.getId() == fromId)
                    from = n;
                if (n.getId() == toId)
                    to = n;
            }
            if (from != null)
                e.addNode(from);
            if (to != null)
                e.addNode(to);
            edges.add(e);
        }
        return edges;
    }
}
