// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/************************************************************/
/**
 * The main game controller.
 * Manages players, agents, the board, and the game loop.
 * Turn automaton: roll → resolve (robber if 7) → choose action.
 */
public class Game {
    private static final Logger LOGGER = Logger.getLogger(Game.class.getName());

    private List<Player> players;
    private Board board;
    private int round;
    private Configuration configuration;
    private List<IAgent> agents;
    private ResourceBank resourceBank;
    private GameStateExporter gameStateExporter;
    private Random random;

    public Game(Board board, List<Player> players, List<IAgent> agents) {
        this.board = board;
        this.players = new ArrayList<>(players);
        this.agents = new ArrayList<>(agents);
        this.round = 0;
        this.configuration = new Configuration();
        this.resourceBank = new ResourceBank();
        this.gameStateExporter = new GameStateExporter();
        this.random = new Random();
    }

    public int getRound() {
        return round;
    }

    public Board getBoard() {
        return board;
    }

    public List<Player> getPlayers() {
        return players;
    }

    public ResourceBank getResourceBank() {
        return resourceBank;
    }

    public Configuration getConfiguration() {
        return configuration;
    }

    public GameStateExporter getGameStateExporter() {
        return gameStateExporter;
    }

    /**
     * Runs the full game until termination.
     */
    public void startGame() {
        LOGGER.info("=== Catan Simulation Started ===");
        while (!checkTermination()) {
            playRound();
            printRoundSummary();
            gameStateExporter.writeState(this);
        }
        Player winner = getWinner();
        if (winner != null) {
            LOGGER.log(Level.INFO, "\n=== Game Over! Winner: Player {0} with {1} VP ===",
                    new Object[] { winner.getId(), winner.getVictoryPoints() });
        } else {
            LOGGER.info("\n=== Game Over! Max rounds reached. No winner. ===");
        }
    }

    /**
     * Plays a single round: each agent takes a turn following the automaton.
     * Roll → resolve robber if 7 → choose action.
     */
    public void playRound() {
        round++;
        for (int i = 0; i < agents.size(); i++) {
            IAgent agent = agents.get(i);
            Player player = players.get(i);

            // If this is a HumanAgent, wait for "go" before the turn
            if (agent instanceof HumanAgent humanAgent) {
                humanAgent.waitForGo();
            }

            // Roll dice
            int diceRoll = rollDiceForPlayer();
            LOGGER.log(Level.INFO, "Player {0} rolled: {1}", new Object[] { player.getId(), diceRoll });

            // Resolve roll
            distributeResources(diceRoll);

            // Robber check
            if (diceRoll == 7) {
                resolveRobber(player);
            }

            // Agent chooses and returns an action
            Action action = agent.takeTurn(round, board, resourceBank);
            LOGGER.log(Level.INFO, "  {0}", action);

            if (action != null) {
                applyAction(action, player);
            }

            // Overwrite state.json after each turn/action (per user request)
            gameStateExporter.writeState(this);
        }
    }

    /**
     * Executes the parsed Action on the game state (mutating board and player
     * structures).
     * If the action comes from an AI (missing node IDs), it picks the first valid
     * placement.
     */
    private void applyAction(Action action, Player player) {
        if (action.getActionType() == null)
            return;

        switch (action.getActionType()) {
            case BUILD_SETTLEMENT:
                handleBuildSettlement(action, player);
                break;
            case BUILD_CITY:
                handleBuildCity(action, player);
                break;
            case BUILD_ROAD:
                handleBuildRoad(action, player);
                break;
            default:
                break;
        }
    }

    private void handleBuildSettlement(Action action, Player player) {
        try {
            String[] parts = action.getDescription().split(" ");
            if (parts.length > 1) {
                int nodeId = Integer.parseInt(parts[1]);
                Node n = board.getNode(nodeId);
                if (n != null && board.isValidSettlementPlacement(n, player)) {
                    Settlement s = new Settlement(player, n);
                    player.addStructure(s);
                    LOGGER.log(Level.INFO, "    Successfully built Settlement at node {0}", nodeId);
                } else {
                    LOGGER.log(Level.INFO, "    Failed: Invalid settlement placement at node {0}", nodeId);
                }
            } else {
                for (Node n : board.getNodes()) {
                    if (board.isValidSettlementPlacement(n, player)) {
                        Settlement s = new Settlement(player, n);
                        player.addStructure(s);
                        LOGGER.log(Level.INFO, "    AI successfully built Settlement at node {0}", n.getId());
                        break;
                    }
                }
            }
        } catch (NumberFormatException e) {
            LOGGER.log(Level.SEVERE, "Failed to parse node ID for settlement", e);
        }
    }

    private void handleBuildCity(Action action, Player player) {
        try {
            String[] parts = action.getDescription().split(" ");
            if (parts.length > 1) {
                int nodeId = Integer.parseInt(parts[1]);
                Node n = board.getNode(nodeId);
                if (n != null && board.isValidCityPlacement(n, player)) {
                    City c = new City(player, n);
                    player.getStructures()
                            .removeIf(st -> st.getLocation() != null && st.getLocation().getId() == nodeId);
                    player.addStructure(c);
                    LOGGER.log(Level.INFO, "    Successfully built City at node {0}", nodeId);
                } else {
                    LOGGER.log(Level.INFO, "    Failed: Invalid city placement at node {0}", nodeId);
                }
            } else {
                for (Node n : board.getNodes()) {
                    if (board.isValidCityPlacement(n, player)) {
                        City c = new City(player, n);
                        player.getStructures()
                                .removeIf(st -> st.getLocation() != null && st.getLocation().getId() == n.getId());
                        player.addStructure(c);
                        LOGGER.log(Level.INFO, "    AI successfully built City at node {0}", n.getId());
                        break;
                    }
                }
            }
        } catch (NumberFormatException e) {
            LOGGER.log(Level.SEVERE, "Failed to parse node ID for city", e);
        }
    }

    private void handleBuildRoad(Action action, Player player) {
        try {
            String[] parts = action.getDescription().split(" ");
            if (parts.length > 2) {
                int fromId = Integer.parseInt(parts[1]);
                int toId = Integer.parseInt(parts[2]);
                Edge targetEdge = findEdge(fromId, toId);
                if (targetEdge != null && board.isValidRoadPlacement(targetEdge, player)) {
                    Road r = new Road(player, targetEdge);
                    targetEdge.setRoad(r);
                    LOGGER.info(() -> String.format("    Successfully built Road from %d to %d", fromId, toId));
                } else {
                    LOGGER.info(() -> String.format("    Failed: Invalid road placement from %d to %d", fromId, toId));
                }
            } else {
                for (Edge e : board.getEdges()) {
                    if (board.isValidRoadPlacement(e, player)) {
                        Road r = new Road(player, e);
                        e.setRoad(r);
                        LOGGER.log(Level.INFO, "    AI successfully built Road on edge {0}", e.getId());
                        break;
                    }
                }
            }
        } catch (NumberFormatException e) {
            LOGGER.log(Level.SEVERE, "Failed to parse node IDs for road", e);
        }
    }

    private Edge findEdge(int fromId, int toId) {
        for (Edge e : board.getEdges()) {
            if (e.getNodes().size() == 2) {
                int id1 = e.getNodes().get(0).getId();
                int id2 = e.getNodes().get(1).getId();
                if ((id1 == fromId && id2 == toId) || (id1 == toId && id2 == fromId)) {
                    return e;
                }
            }
        }
        return null;
    }

    private int rollDiceForPlayer() {
        return (random.nextInt(6) + 1) + (random.nextInt(6) + 1);
    }

    private void distributeResources(int diceRoll) {
        for (Tile tile : board.getTiles()) {
            if (tile.getNumber() == diceRoll && !isRobberOnTile(tile)) {
                processTileResources(tile);
            }
        }
    }

    private boolean isRobberOnTile(Tile tile) {
        return board.getRobber().getLocation() != null
                && board.getRobber().getLocation().getId() == tile.getId();
    }

    private void processTileResources(Tile tile) {
        for (Node node : board.getNodes()) {
            if (node.getStructure() != null) {
                Player owner = node.getStructure().getOwner();
                int amount = node.getStructure().getVictoryPoints();
                if (resourceBank.hasResource(tile.getResourceType(), amount)) {
                    resourceBank.takeResource(tile.getResourceType(), amount);
                    owner.getResourceHand().add(tile.getResourceType(), amount);
                }
            }
        }
    }

    private void resolveRobber(Player roller) {
        LOGGER.info("  *** Robber activated! ***");

        for (Player p : players) {
            if (p.needsToSpendCards()) {
                int totalCards = p.getResourceHand().getTotalCards();
                int cardsToLose = totalCards / 2;
                LOGGER.log(Level.INFO, "  Player {0} has {1} cards, must discard {2}",
                        new Object[] { p.getId(), totalCards, cardsToLose });
                discardRandomCards(p, cardsToLose);
            }
        }

        List<Tile> tiles = board.getTiles();
        if (!tiles.isEmpty()) {
            Tile target = tiles.get(random.nextInt(tiles.size()));
            board.getRobber().move(target);
            LOGGER.log(Level.INFO, "  Robber moved to tile {0}", target.getId());
        }

        List<Player> stealCandidates = new ArrayList<>();
        for (Player p : players) {
            if (p.getId() != roller.getId() && p.getResourceHand().getTotalCards() > 0) {
                stealCandidates.add(p);
            }
        }
        if (!stealCandidates.isEmpty()) {
            Player victim = stealCandidates.get(random.nextInt(stealCandidates.size()));
            ResourceType stolenType = getRandomOwnedResource(victim);
            if (stolenType != null) {
                victim.getResourceHand().remove(stolenType, 1);
                roller.getResourceHand().add(stolenType, 1);
                LOGGER.log(Level.INFO, "  Player {0} stole 1 {1} from Player {2}",
                        new Object[] { roller.getId(), stolenType, victim.getId() });
            }
        }
    }

    private void discardRandomCards(Player player, int count) {
        for (int i = 0; i < count; i++) {
            ResourceType type = getRandomOwnedResource(player);
            if (type != null) {
                player.getResourceHand().remove(type, 1);
                resourceBank.returnResource(type, 1);
            }
        }
    }

    private ResourceType getRandomOwnedResource(Player player) {
        List<ResourceType> owned = new ArrayList<>();
        for (ResourceType type : ResourceType.values()) {
            if (player.getResourceHand().getAmount(type) > 0) {
                owned.add(type);
            }
        }
        if (owned.isEmpty()) {
            return null;
        }
        return owned.get(random.nextInt(owned.size()));
    }

    public boolean checkTermination() {
        for (Player p : players) {
            if (p.getVictoryPoints() >= 10) {
                return true;
            }
        }
        return round >= configuration.getMaxRounds();
    }

    public Player getWinner() {
        Player best = null;
        for (Player p : players) {
            if (best == null || p.getVictoryPoints() > best.getVictoryPoints()) {
                best = p;
            }
        }
        return (best != null && best.getVictoryPoints() >= 10) ? best : null;
    }

    public void printRoundSummary() {
        LOGGER.log(Level.INFO, "\n--- Round {0} Summary ---", round);
        for (Player p : players) {
            LOGGER.log(Level.INFO, "  Player {0}: VP={1}, Cards={2}",
                    new Object[] { p.getId(), p.getVictoryPoints(), p.getResourceHand().getTotalCards() });
        }
    }
}
