// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/************************************************************/
/**
 * A human-controlled agent that reads commands from the console.
 * Implements IAgent directly (does NOT extend Agent) per UML.
 *
 * Turn flow: waitForGo() → roll → parse commands → return Action.
 */
public class HumanAgent implements IAgent {

    private static final Logger LOGGER = Logger.getLogger(HumanAgent.class.getName());

    private Scanner scanner;
    private CommandParser parser;
    private Player player;

    public HumanAgent(Player player) {
        this.player = player;
        this.scanner = new Scanner(System.in);
        this.parser = new CommandParser();
    }

    /**
     * Allows injection of a Scanner for testing.
     */
    public HumanAgent(Player player, Scanner scanner) {
        this.player = player;
        this.scanner = scanner;
        this.parser = new CommandParser();
    }

    public Player getPlayer() {
        return player;
    }

    /**
     * Turn automaton for human player:
     * 1. Display prompt
     * 2. Read and parse command
     * 3. Return the resulting Action
     */
    @Override
    public Action takeTurn(Game game) {
        int roundNumber = game.getRound();
        LOGGER.log(Level.INFO, "\n=== Player {0}''s turn (Round {1}) ===",
                new Object[] { player.getId(), roundNumber });
        LOGGER.log(Level.INFO, "Your resources: {0} (Total VP: {1})", 
                new Object[] { player.getResourceHand().getResources(), player.getVictoryPoints() });
        LOGGER.info("Commands: roll, list, build settlement <nodeId>, build city <nodeId>, build road <fromNodeId> <toNodeId>, pass");

        while (true) {
            LOGGER.info("> ");
            if (!scanner.hasNextLine()) {
                // EOF — pass
                return new Action(roundNumber, player.getId(), "PASS", ActionType.PASS);
            }
            String input = scanner.nextLine().trim();

            if (input.isEmpty()) {
                continue;
            }

            Action action = parser.parse(input);
            if (action != null) {
                // Fill in the round and player info
                return new Action(roundNumber, player.getId(), action.getDescription(), action.getActionType());
            } else {
                LOGGER.info(
                        "Invalid command. Try: roll, list, build settlement <nodeId>, build city <nodeId>, build road <from> <to>, pass");
            }
        }
    }

    // Removed waitForGo as it is now naturally handled by the command loop.
}
