// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * Interface for all agents (machine or human) that can take turns.
 */
public interface IAgent {

    /**
     * Take a turn in the game.
     *
     * @param game          the game controller instance
     * @return the Action chosen during this turn
     */
    Action takeTurn(Game game);
}
