// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public enum ResourceType {
	/**
	 * 
	 */
	BRICK,
	/**
	 * 
	 */
	WOOL,
	/**
	 * 
	 */
	LUMBER,
	/**
	 * 
	 */
	GRAIN,
	/**
	 * 
	 */
	ORE,
	/**
	 * 
	 */
	DESERT;
}
