// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * A hex tile on the board with a resource type and dice number.
 */
public class Tile {

    private int id;
    private ResourceType resourceType;
    private int number;
    private List<Node> nodes;

    public Tile(int id, ResourceType resourceType, int number) {
        this.id = id;
        this.resourceType = resourceType;
        this.number = number;
        this.nodes = new ArrayList<>();
    }

    public int getId() {
        return id;
    }

    public ResourceType getResourceType() {
        return resourceType;
    }

    public int getNumber() {
        return number;
    }

    public List<Node> getNodes() {
        return nodes;
    }

    public void addNode(Node node) {
        if (node != null && !nodes.contains(node)) {
            nodes.add(node);
        }
    }
}
